# Generated by Django 5.0.3 on 2024-04-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_modelmaxx_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='app/static', verbose_name='Ваше фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='modelmaxx',
            name='file',
        ),
        migrations.AddField(
            model_name='modelmaxx',
            name='user_image',
            field=models.ImageField(null=True, upload_to='app/static'),
        ),
    ]
