# Generated by Django 5.0.3 on 2024-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_modelmaxx_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmaxx',
            name='file',
            field=models.FileField(null=True, upload_to='{% static %}'),
        ),
    ]
