# Generated by Django 5.0.3 on 2024-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_modelmaxx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmaxx',
            name='email',
            field=models.EmailField(max_length=80),
        ),
    ]
